# Uncomment the next line to define a global platform for your project

target 'KGDownloader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iMusic
  pod 'Alamofire', '5.8.1'  
end
